package s3.individual.vinylo.domain.Mappers;

import s3.individual.vinylo.domain.Vinyl;
import s3.individual.vinylo.persistence.entity.VinylEntity;

public class VinylEntityMapper {

    // Converts Vinyl domain object to VinylEntity
    public static VinylEntity toEntity(Vinyl vinyl) {
        if (vinyl == null) {
            return null;
        }

        VinylEntity entity = new VinylEntity();
        // Do not set ID, as it's auto-generated by the database
        entity.setTitle(vinyl.getTitle());
        entity.setDescription(vinyl.getDescription());
        entity.setIsReleased(vinyl.getisReleased());
        entity.setVinylType(vinyl.getvinylType());
        entity.setArtist(ArtistEntityMapper.toEntity(vinyl.getArtist()));

        return entity;
    }

    // Converts VinylEntity to Vinyl domain object
    public static Vinyl fromEntity(VinylEntity entity) {
        if (entity == null) {
            return null;
        }

        Vinyl vinyl = new Vinyl();
        vinyl.setId(entity.getId()); // Retrieve the auto-generated ID from the entity
        vinyl.setTitle(entity.getTitle());
        vinyl.setDescription(entity.getDescription());
        vinyl.setIsReleased(entity.getIsReleased());
        vinyl.setVinylType(entity.getVinylType());
        vinyl.setArtist(ArtistEntityMapper.fromEntity(entity.getArtist()));

        return vinyl;
    }
}
